find-dir-with = $(shell /usr/bin/perl -e 'chomp($$_ = `pwd`); while ($$_ ne "" && ! -e "$$_/$(1)") { m:(.*)/[^/]+/??:; $$_ = $$1; } print;')

ifndef BSG_MANYCORE_DIR
  export BSG_MANYCORE_DIR := $(call find-dir-with,.BSG_MANYCORE_ROOT)
endif

$(warning $(BSG_MANYCORE_DIR))

bsg_tiles_X= 1
bsg_tiles_Y= 1

include $(BSG_MANYCORE_DIR)/software/mk/Makefile.master

.DEFAULT_GOAL := selected

# This logic adds the risc-v test directories to the vpath
# each test has a single .S file with a unique name

RVTEST_DIR = $(BSG_MANYCORE_DIR)/imports/riscv-tests/isa

# RVTEST_ISA_VARIANTS is exported by parent makefile
RVTEST_ASM_DIRs = $(foreach test_isa, $(RVTEST_ISA_VARIANTS), $(RVTEST_DIR)/$(test_isa))

vpath %.S $(RVTEST_ASM_DIRs)

# Parent directory has the modified header "riscv_test.h", which
# will override the original one.
RVTEST_INCS = -I.. -I$(RVTEST_DIR)/macros/scalar

INCS += $(RVTEST_INCS)
RISCV_LINK_OPTS = -march=rv32ima -nostdlib -nostartfiles

%.riscv:  %.o
	$(RISCV_LINK) $< -o $@ $(RISCV_LINK_OPTS)

# Set a separate program run for each run
%.run: PROG_NAME=$(basename $@)


include $(BSG_MANYCORE_DIR)/software/mk/Makefile.tail_rules
