include arch_filelist.mk
include sim_filelist.mk
include tb_filelist.mk

VDEFINES  := $(ARCH_VDEFINES) $(SIM_VDEFINES) $(TB_VDEFINES)
VSOURCES  := $(ARCH_VSOURCES) $(SIM_VSOURCES) $(TB_VSOURCES)
VINCDIRS  := $(ARCH_VINCDIRS) $(SIM_VINCDIRS) $(TB_VINCDIRS)
VINCLUDES := $(foreach dir, $(VINCDIRS), $(shell find $(dir) -name '*.vh'))

VCS_DEFINES  := $(VDEFINES)
VCS_SOURCES  := $(VSOURCES)
VCS_INCDIRS  := $(foreach dir, $(VINCDIRS), +incdir+$(dir))
VCS_INCLUDES := $(VINCLUDES)
