include arch_filelist.mk
include sim_filelist.mk
include tb_filelist.mk

VDEFINES  := $(ARCH_VDEFINES) $(SIM_VDEFINES) $(TB_VDEFINES)
VSOURCES  := $(ARCH_VSOURCES) $(SIM_VSOURCES) $(TB_VSOURCES)
VINCLUDES := $(ARCH_VINCLUDES) $(SIM_VINCLUDES) $(TB_VINCLUDES)

VCS_DEFINES  := $(VDEFINES)
VCS_SOURCES  := $(VSOURCES)
VCS_INCLUDES := $(foreach dir, $(VINCLUDES), +incdir+$(dir))
