ifeq ($(BSG_PLATFORM),verilator)
BSG_MACHINE ?= pod_1x1_2X2Y
else ifeq ($(BSG_PLATFORM),vcs)
BSG_MACHINE ?= pod_1x1_2X2Y
else ifeq ($(BSG_PLATFORM),xcelium)
BSG_MACHINE ?= pod_1x1_2X2Y
endif
BSG_MACHINE_PATH ?= $(BSG_MANYCORE_DIR)/machines/$(BSG_MACHINE)

ifeq (,$(findstring $(BSG_MACHINE),$(BSG_MACHINE_PATH)))
$(error BSG_MACHINE $(BSG_MACHINE) is inconsistent with $(BSG_MACHINE_PATH))
endif

