%.echo:
	echo $($*)

dve:
	$(VCS_BIN)/dve -full64 -vpd vcdplus.vpd &

%.pelog: pe.log
	cat pe.log | grep '^$@' | sed 's/$@ //' > $@

urg:
	$(VCS_BIN)/urg -full64 -report coverage/ -format both -dir *.vdb/

clean:
	-rm -rf *.o *.jou *.log *.pelog *.pb bsg_manycore_io_complex_rom.v *.riscv *.wdb *.bin *.hex
	-rm -rf xsim.dir *.mem
	-rm -rf ./simv csrc simv.daidir ucli.key DVEfiles *.vpd *.vdb coverage/
