import argparse
import common
from __init__ import *

msg = """
The interface for parsing COSIM output logs. This parser comprises
of following five tools:

- blood_graph
- stats_parser
- pc_histogram
- trace_parser
- vcache_stall_graph

By default blood_graph, stats_parser and pc_histogram are executed,
given required files are generated by cosim. If required files for
a tool are missing it is skipped.
"""

parser = argparse.ArgumentParser(
    description=msg,
    formatter_class=argparse.RawDescriptionHelpFormatter,
    prog="vanilla_parser",
    conflict_handler='error')

common.add_args(parser)

# Load command line options of all parser submodules
blood_graph.add_args(
    parser.add_argument_group('Blood graph specific options'))
stats_parser.add_args(
    parser.add_argument_group('Stats parser specific options'))
pc_histogram.add_args(
    parser.add_argument_group('PC histogram specific options'))
vcache_stall_graph.add_args(
    parser.add_argument_group('Vcache stall graph specific options'))

# Parse arguments
args = parser.parse_args()

common.check_exists_and_run(
    [args.trace, args.stats], blood_graph.main, args)
common.check_exists_and_run(
    [args.trace], pc_histogram.main, args)
common.check_exists_and_run(
    [args.stats], stats_parser.main, args)

# Currently vcache stall graph prints to std out, we can enable this if the output is
# directed to standard set of file and decide that what the default input is going to
# be.
#
#common.check_exists_and_run(
#    [args.vcache_trace, args.vcache_stats], vcache_stall_graph.main, args)
